# AIXPM: main - Download and Install Package (from AIXTOOLS)
#############################
# Include Package variables #
#############################
---
- name: Include Package variables
  include_vars: "./vars/{{ pkg_name }}.yml"

# Check to see if a file that is included in package already exists
# Block below will skip if file exists.
- name: "Check status of {{ pkg_creates }}"
  stat:
    path: "{{ pkg_creates }}"
  register: tgt
- block:
  - name: Get PPID
    shell: 'echo $PPID'
    register: ppid
    changed_when: false
  - name: "Create {{ images }}.{{ ppid.stdout }}"
    file:
      path: "{{ images }}.{{ ppid.stdout }}"
      state: directory
  - name: "Download files for package {{ pkg_name }}"
    get_url:
      url: "{{item.src_t}}://{{item.src}}{{item.lpp}}.{{item.vrmf}}.I"
      checksum: "{{ item.chksum }}"
      dest: "{{ images }}.{{ ppid.stdout }}"
    with_items:
      - "{{ packages }}"
  - name: "Install {{ pkg_name }}"
    command:
      cmd: "/usr/sbin/installp -d {{ images }}.{{ ppid.stdout }} -agYX all"
      creates: "{{ pkg_creates }}"
    register: installp
  - name: Cleanup {{ images }}.{{ ppid.stdout }}
    file: "path={{ images }}.{{ ppid.stdout }} state=absent"
  when: tgt.stat.exists == false
